//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFGapple.Language {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFGapple.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   64GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string altmisdortgb {
            get {
                return ResourceManager.GetString("altmisdortgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try Auto Login Module: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string autologin {
            get {
                return ResourceManager.GetString("autologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Can&apos;t Catch The Error, Please Write A Issue On GitHub! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string catchno {
            get {
                return ResourceManager.GetString("catchno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dortgb {
            get {
                return ResourceManager.GetString("dortgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do You Want To Do Fresh Install? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fresh {
            get {
                return ResourceManager.GetString("fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple - Have Fun :) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fun {
            get {
                return ResourceManager.GetString("fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string giriscrack {
            get {
                return ResourceManager.GetString("giriscrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string girismojang {
            get {
                return ResourceManager.GetString("girismojang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take Me Back! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string grdn {
            get {
                return ResourceManager.GetString("grdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ikigb {
            get {
                return ResourceManager.GetString("ikigb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Your Connection! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string inthata {
            get {
                return ResourceManager.GetString("inthata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Main System Is Damaged! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mainbroke {
            get {
                return ResourceManager.GetString("mainbroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is this? This optimization tool looks for the amount of memory in your system and allocates enough memory for the game. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string memred {
            get {
                return ResourceManager.GetString("memred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Mod Folder ⤵ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string modfolder {
            get {
                return ResourceManager.GetString("modfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong E-Mail or Password! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mojhata {
            get {
                return ResourceManager.GetString("mojhata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a Nickname! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string nick {
            get {
                return ResourceManager.GetString("nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string onaltigb {
            get {
                return ResourceManager.GetString("onaltigb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I Have A Original Account! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string orjhesap {
            get {
                return ResourceManager.GetString("orjhesap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string otuzikigb {
            get {
                return ResourceManager.GetString("otuzikigb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ping Process Failed! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pinghata {
            get {
                return ResourceManager.GetString("pinghata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nickname or E-Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string place1 {
            get {
                return ResourceManager.GetString("place1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string place2 {
            get {
                return ResourceManager.GetString("place2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play ▶ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string prep {
            get {
                return ResourceManager.GetString("prep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready For Launch! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple - Resources Loading benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string resor {
            get {
                return ResourceManager.GetString("resor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sekizgb {
            get {
                return ResourceManager.GetString("sekizgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Cannot Be Started, Select A Version For Start The Game! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selver {
            get {
                return ResourceManager.GetString("selver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Updates Automatically: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set1 {
            get {
                return ResourceManager.GetString("set1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Other Versions: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set2 {
            get {
                return ResourceManager.GetString("set2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set3 {
            get {
                return ResourceManager.GetString("set3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set4 {
            get {
                return ResourceManager.GetString("set4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit After The Starting To Game: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string setname {
            get {
                return ResourceManager.GetString("setname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string setto {
            get {
                return ResourceManager.GetString("setto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Started! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string started {
            get {
                return ResourceManager.GetString("started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Cannot Start The Game, Please Check Your FireWall. If Your System OK, Contact From GitHub. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string startfail {
            get {
                return ResourceManager.GetString("startfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple - Updates Disabled benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string upbroke {
            get {
                return ResourceManager.GetString("upbroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Cannot Get The Version List! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string verno {
            get {
                return ResourceManager.GetString("verno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Version: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string versel {
            get {
                return ResourceManager.GetString("versel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome Back:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
